# This file is DEPRECATED and can be deleted.
# Firebase dependencies are now managed via Swift Package Manager (SPM).
#
# To add Firebase to the project:
# 1. Open iosApp.xcodeproj in Xcode
# 2. Go to File > Add Package Dependencies...
# 3. Enter: https://github.com/firebase/firebase-ios-sdk
# 4. Select FirebaseAuth and FirebaseCore packages

